# Generated by Django 3.0.6 on 2020-06-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category_Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300)),
                ('bookie_first_name', models.CharField(max_length=50)),
                ('bookie_last_name', models.CharField(max_length=50)),
                ('bookie_phone', models.IntegerField()),
                ('bookie_email', models.EmailField(max_length=254)),
                ('bookie_address', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('event_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('payment_status', models.CharField(choices=[('Due', 'Due'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='due', max_length=20)),
                ('alt_first_name', models.CharField(max_length=50)),
                ('alt_last_name', models.CharField(max_length=50)),
                ('alt_phone', models.IntegerField()),
                ('alt_email', models.EmailField(max_length=254)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category_Auth.Category')),
            ],
        ),
    ]
